### ISSUE TITLE
[Bug]: nothing at all happens unless darshan log has DXT information

### ISSUE THREAD

**Issue by roblatham00** [hpc-io/dxt-explorer#12]
### What happened?

I ran dxt-explorer on a darshan file without any DXT data.  DXT-explorer produced no web page.  

Version:  dxt-explorer @main

### What did you expect to happen?

Maybe a warning "hey there is no DXT data in here" or an empty web page saying something similar

### Version

0.2 (Default)

### Relevant log output

```shell
% python3 ./explore/dxt.py --browser ~/work/benvolio/summit/e3sm-io/robl_bv-server_id109925_3-3-58193-11625755438384278452_1.darshan
/home/robl/work/dxt-explorer/./explore/dxt.py:33: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
2022-08-08 15:04:53,705 dxt - INFO - 37 I/O trace observation records from 0 files
2022-08-08 15:04:53,705 dxt - INFO - generating datasets
|████████████████████████████████████████| (!) 0 in 0.1s
|████████████████████████████████████████| (!) 0 in 0.1s
```

**Comment by jeanbez** [comment]
@roblatham00, this should be fixed in the latest version (PR #15), but please let me know if you still run into this issue!
